import { intro, outro, text, select, confirm, isCancel, cancel } from '@clack/prompts';
import { MempalaceConfig } from '../core/config';
import { EntityRegistry, RegistryEntity } from '../core/entity_registry';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';

export async function runOnboarding() {
  intro('Welcome to MemPalace JS Setup');

  const config = new MempalaceConfig();
  const registry = new EntityRegistry();

  const mode = await select({
    message: 'How are you using MemPalace?',
    options: [
      { value: 'work', label: 'Work', hint: 'notes, projects, clients, colleagues' },
      { value: 'personal', label: 'Personal', hint: 'diary, family, health, reflections' },
      { value: 'combo', label: 'Both', hint: 'mixed professional and personal' }
    ]
  });

  if (isCancel(mode)) {
    cancel('Setup cancelled.');
    process.exit(0);
  }

  const people: RegistryEntity[] = [];
  const projects: string[] = [];

  const addPeople = await confirm({
    message: 'Would you like to register important people in your life?'
  });

  if (addPeople && !isCancel(addPeople)) {
    let adding = true;
    while (adding) {
      const name = await text({ message: 'Enter name (or leave blank to finish):' });
      if (isCancel(name) || !name) {
          adding = false;
          continue;
      }
      const relationship = await text({ message: `What is your relationship to ${name}?` });
      people.push({
          name: name as string,
          type: 'person',
          confidence: 1.0,
          source: 'onboarding',
          relationship: relationship as string,
          contexts: [mode as string]
      });
    }
  }

  if (mode !== 'personal') {
      const addProjects = await confirm({ message: 'Would you like to register your main projects?' });
      if (addProjects && !isCancel(addProjects)) {
          let adding = true;
          while (adding) {
              const proj = await text({ message: 'Enter project name (or leave blank to finish):' });
              if (isCancel(proj) || !proj) {
                  adding = false;
                  continue;
              }
              projects.push(proj as string);
          }
      }
  }

  // Seed Registry
  registry.seed(mode as any, people, projects);

  // Generate Bootstrap Files
  generateBootstrapFiles(people, projects, mode as string);

  const shouldMine = await confirm({
    message: 'Would you like to mine a project folder now?',
  });

  if (!isCancel(shouldMine) && shouldMine) {
    const projectDir = await text({
      message: 'Enter the project path to mine:',
      initialValue: process.cwd()
    });
    if (!isCancel(projectDir)) {
        console.log(`Mining project at ${projectDir}...`);
        // Implementation of mining would go here or be triggered later
    }
  }

  config.init();
  outro('MemPalace initialized successfully with persona and entity bootstrapping!');
}

function generateBootstrapFiles(people: RegistryEntity[], projects: string[], mode: string) {
    const mempalaceDir = path.join(os.homedir(), '.mempalace');
    if (!fs.existsSync(mempalaceDir)) fs.mkdirSync(mempalaceDir, { recursive: true });

    // 1. AAAK Entities
    let aaak = "# AAAK Entity Registry\n# Auto-generated by mempalace init\n\n## People\n";
    people.forEach(p => {
        const code = p.name.substring(0, 3).toUpperCase();
        aaak += `  ${code}=${p.name} (${p.relationship || ''})\n`;
    });
    if (projects.length > 0) {
        aaak += "\n## Projects\n";
        projects.forEach(p => {
            const code = p.substring(0, 4).toUpperCase();
            aaak += `  ${code}=${p}\n`;
        });
    }
    fs.writeFileSync(path.join(mempalaceDir, 'aaak_entities.md'), aaak);

    // 2. Critical Facts
    let facts = "# Critical Facts (bootstrap)\n\n";
    if (people.length > 0) {
        facts += "## People\n";
        people.forEach(p => {
            facts += `- **${p.name}** — ${p.relationship || 'Contact'}\n`;
        });
    }
    if (projects.length > 0) {
        facts += "\n## Projects\n";
        projects.forEach(p => facts += `- **${p}**\n`);
    }
    facts += `\n## Context\nMode: ${mode}\n`;
    fs.writeFileSync(path.join(mempalaceDir, 'critical_facts.md'), facts);
}
