/** Generated from dialect.py */

export const EMOTION_SIGNALS: Record<string, string> = {
  'decided': "determ",
  'prefer': "convict",
  'worried': "anx",
  'excited': "excite",
  'frustrated': "frust",
  'confused': "confuse",
  'love': "love",
  'hate': "rage",
  'hope': "hope",
  'fear': "fear",
  'trust': "trust",
  'happy': "joy",
  'sad': "grief",
  'surprised': "surprise",
  'grateful': "grat",
  'curious': "curious",
  'wonder': "wonder",
  'anxious': "anx",
  'relieved': "relief",
  'satisf': "satis",
  'disappoint': "grief",
  'concern': "anx",
};
export const FLAG_SIGNALS: Record<string, string> = {
  'decided': "DECISION",
  'chose': "DECISION",
  'switched': "DECISION",
  'migrated': "DECISION",
  'replaced': "DECISION",
  'instead of': "DECISION",
  'because': "DECISION",
  'founded': "ORIGIN",
  'created': "ORIGIN",
  'started': "ORIGIN",
  'born': "ORIGIN",
  'launched': "ORIGIN",
  'first time': "ORIGIN",
  'core': "CORE",
  'fundamental': "CORE",
  'essential': "CORE",
  'principle': "CORE",
  'belief': "CORE",
  'always': "CORE",
  'never forget': "CORE",
  'turning point': "PIVOT",
  'changed everything': "PIVOT",
  'realized': "PIVOT",
  'breakthrough': "PIVOT",
  'epiphany': "PIVOT",
  'api': "TECHNICAL",
  'database': "TECHNICAL",
  'architecture': "TECHNICAL",
  'deploy': "TECHNICAL",
  'infrastructure': "TECHNICAL",
  'algorithm': "TECHNICAL",
  'framework': "TECHNICAL",
  'server': "TECHNICAL",
  'config': "TECHNICAL",
};
export const STOP_WORDS: Set<string> = new Set([
  'a',
  'about',
  'above',
  'after',
  'again',
  'all',
  'also',
  'an',
  'and',
  'are',
  'as',
  'at',
  'be',
  'because',
  'been',
  'before',
  'being',
  'below',
  'between',
  'both',
  'but',
  'by',
  'can',
  'could',
  'did',
  'do',
  'does',
  'don',
  'down',
  'during',
  'each',
  'every',
  'few',
  'for',
  'from',
  'further',
  'get',
  'got',
  'had',
  'has',
  'have',
  'he',
  'her',
  'here',
  'him',
  'his',
  'how',
  'i',
  'if',
  'in',
  'into',
  'is',
  'it',
  'its',
  'just',
  'like',
  'made',
  'make',
  'many',
  'may',
  'me',
  'might',
  'more',
  'most',
  'much',
  'my',
  'need',
  'no',
  'nor',
  'not',
  'now',
  'of',
  'off',
  'on',
  'once',
  'only',
  'or',
  'other',
  'our',
  'out',
  'over',
  'own',
  'really',
  'same',
  'shall',
  'she',
  'should',
  'since',
  'so',
  'some',
  'such',
  'than',
  'that',
  'the',
  'their',
  'them',
  'then',
  'there',
  'these',
  'they',
  'thing',
  'things',
  'this',
  'those',
  'through',
  'to',
  'too',
  'under',
  'up',
  'us',
  'use',
  'used',
  'using',
  'very',
  'want',
  'was',
  'way',
  'we',
  'well',
  'were',
  'what',
  'when',
  'where',
  'which',
  'while',
  'who',
  'whom',
  'why',
  'will',
  'with',
  'would',
  'you',
  'your',
]);

export const EMOTION_CODES: Record<string, string> = {
  "vulnerability": "vul",
  "vulnerable": "vul",
  "joy": "joy",
  "joyful": "joy",
  "fear": "fear",
  "mild_fear": "fear",
  "trust": "trust",
  "trust_building": "trust",
  "grief": "grief",
  "raw_grief": "grief",
  "wonder": "wonder",
  "philosophical_wonder": "wonder",
  "rage": "rage",
  "anger": "rage",
  "love": "love",
  "devotion": "love",
  "hope": "hope",
  "despair": "despair",
  "hopelessness": "despair",
  "peace": "peace",
  "relief": "relief",
  "humor": "humor",
  "dark_humor": "humor",
  "tenderness": "tender",
  "raw_honesty": "raw",
  "brutal_honesty": "raw",
  "self_doubt": "doubt",
  "anxiety": "anx",
  "exhaustion": "exhaust",
  "conviction": "convict",
  "quiet_passion": "passion",
  "warmth": "warmth",
  "curiosity": "curious",
  "gratitude": "grat",
  "frustration": "frust",
  "confusion": "confuse",
  "satisfaction": "satis",
  "excitement": "excite",
  "determination": "determ",
  "surprise": "surprise",
};
