/** Generated from general_extractor.py */

export const DECISION_MARKERS: string[] = [
  '\\blet\'?s (use|go with|try|pick|choose|switch to)\\b',
  '\\bwe (should|decided|chose|went with|picked|settled on)\\b',
  '\\bi\'?m going (to|with)\\b',
  '\\bbetter (to|than|approach|option|choice)\\b',
  '\\binstead of\\b',
  '\\brather than\\b',
  '\\bthe reason (is|was|being)\\b',
  '\\bbecause\\b',
  '\\btrade-?off\\b',
  '\\bpros and cons\\b',
  '\\bover\\b.*\\bbecause\\b',
  '\\barchitecture\\b',
  '\\bapproach\\b',
  '\\bstrategy\\b',
  '\\bpattern\\b',
  '\\bstack\\b',
  '\\bframework\\b',
  '\\binfrastructure\\b',
  '\\bset (it |this )?to\\b',
  '\\bconfigure\\b',
  '\\bdefault\\b',
];
export const PREFERENCE_MARKERS: string[] = [
  '\\bi prefer\\b',
  '\\balways use\\b',
  '\\bnever use\\b',
  '\\bdon\'?t (ever |like to )?(use|do|mock|stub|import)\\b',
  '\\bi like (to|when|how)\\b',
  '\\bi hate (when|how|it when)\\b',
  '\\bplease (always|never|don\'?t)\\b',
  '\\bmy (rule|preference|style|convention) is\\b',
  '\\bwe (always|never)\\b',
  '\\bfunctional\\b.*\\bstyle\\b',
  '\\bimperative\\b',
  '\\bsnake_?case\\b',
  '\\bcamel_?case\\b',
  '\\btabs\\b.*\\bspaces\\b',
  '\\bspaces\\b.*\\btabs\\b',
  '\\buse\\b.*\\binstead of\\b',
];
export const MILESTONE_MARKERS: string[] = [
  '\\bit works\\b',
  '\\bit worked\\b',
  '\\bgot it working\\b',
  '\\bfixed\\b',
  '\\bsolved\\b',
  '\\bbreakthrough\\b',
  '\\bfigured (it )?out\\b',
  '\\bnailed it\\b',
  '\\bcracked (it|the)\\b',
  '\\bfinally\\b',
  '\\bfirst time\\b',
  '\\bfirst ever\\b',
  '\\bnever (done|been|had) before\\b',
  '\\bdiscovered\\b',
  '\\brealized\\b',
  '\\bfound (out|that)\\b',
  '\\bturns out\\b',
  '\\bthe key (is|was|insight)\\b',
  '\\bthe trick (is|was)\\b',
  '\\bnow i (understand|see|get it)\\b',
  '\\bbuilt\\b',
  '\\bcreated\\b',
  '\\bimplemented\\b',
  '\\bshipped\\b',
  '\\blaunched\\b',
  '\\bdeployed\\b',
  '\\breleased\\b',
  '\\bprototype\\b',
  '\\bproof of concept\\b',
  '\\bdemo\\b',
  '\\bversion \\d',
  '\\bv\\d+\\.\\d+',
  '\\d+x (compression|faster|slower|better|improvement|reduction)',
  '\\d+% (reduction|improvement|faster|better|smaller)',
];
export const PROBLEM_MARKERS: string[] = [
  '\\b(bug|error|crash|fail|broke|broken|issue|problem)\\b',
  '\\bdoesn\'?t work\\b',
  '\\bnot working\\b',
  '\\bwon\'?t\\b.*\\bwork\\b',
  '\\bkeeps? (failing|crashing|breaking|erroring)\\b',
  '\\broot cause\\b',
  '\\bthe (problem|issue|bug) (is|was)\\b',
  '\\bturns out\\b.*\\b(was|because|due to)\\b',
  '\\bthe fix (is|was)\\b',
  '\\bworkaround\\b',
  '\\bthat\'?s why\\b',
  '\\bthe reason it\\b',
  '\\bfixed (it |the |by )\\b',
  '\\bsolution (is|was)\\b',
  '\\bresolved\\b',
  '\\bpatched\\b',
  '\\bthe answer (is|was)\\b',
  '\\b(had|need) to\\b.*\\binstead\\b',
];
export const EMOTION_MARKERS: string[] = [
  '\\blove\\b',
  '\\bscared\\b',
  '\\bafraid\\b',
  '\\bproud\\b',
  '\\bhurt\\b',
  '\\bhappy\\b',
  '\\bsad\\b',
  '\\bcry\\b',
  '\\bcrying\\b',
  '\\bmiss\\b',
  '\\bsorry\\b',
  '\\bgrateful\\b',
  '\\bangry\\b',
  '\\bworried\\b',
  '\\blonely\\b',
  '\\bbeautiful\\b',
  '\\bamazing\\b',
  '\\bwonderful\\b',
  'i feel',
  'i\'m scared',
  'i love you',
  'i\'m sorry',
  'i can\'t',
  'i wish',
  'i miss',
  'i need',
  'never told anyone',
  'nobody knows',
  '\\*[^*]+\\*',
];
export const POSITIVE_WORDS: Set<string> = new Set([
  'adore',
  'amazing',
  'beautiful',
  'breakthrough',
  'brilliant',
  'excited',
  'fantastic',
  'fixed',
  'grateful',
  'happy',
  'heart',
  'hug',
  'incredible',
  'joy',
  'love',
  'loving',
  'nailed',
  'perfect',
  'precious',
  'pride',
  'proud',
  'solved',
  'success',
  'thrilled',
  'warm',
  'wonderful',
  'working',
  'works',
]);
export const NEGATIVE_WORDS: Set<string> = new Set([
  'awful',
  'blocked',
  'breaking',
  'breaks',
  'broke',
  'broken',
  'bug',
  'crash',
  'crashed',
  'crashing',
  'disaster',
  'error',
  'fail',
  'failed',
  'failing',
  'failure',
  'horrible',
  'impossible',
  'issue',
  'mess',
  'missing',
  'panic',
  'problem',
  'stuck',
  'terrible',
  'unable',
  'worse',
  'worst',
  'wrong',
]);
export const CODE_LINE_PATTERNS: string[] = [
  '^\\s*[\\$#]\\s',
  '^\\s*(cd|source|echo|export|pip|npm|git|python|bash|curl|wget|mkdir|rm|cp|mv|ls|cat|grep|find|chmod|sudo|brew|docker)\\s',
  '^\\s*```',
  '^\\s*(import|from|def|class|function|const|let|var|return)\\s',
  '^\\s*[A-Z_]{2,}=',
  '^\\s*\\|',
  '^\\s*[-]{2,}',
  '^\\s*[{}[\\]]\\s*$',
  '^\\s*(if|for|while|try|except|elif|else:)\\b',
  '^\\s*\\w+\\.\\w+\\(',
  '^\\s*\\w+ = \\w+\\.\\w+',
];
